[package]
name = "promptis"
version = "0.1.0"
edition = "2021"
authors = ["Shea Frembling"]
description = "Simplify getting user input in the CLI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
